"""добавил таблицу medical_cards и изменил patient

Revision ID: 21287d19e2d9
Revises: c2babe9064e6
Create Date: 2021-06-19 23:23:57.768592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21287d19e2d9'
down_revision = 'c2babe9064e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('illnesses', sa.String(), nullable=True),
    sa.Column('symptoms', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('doctors', sa.Column('surname', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('middle_name', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('sex', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('specialization', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('appointment_times', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('surname', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('middle_name', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('birthday', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('sex', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('medical_card_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patients', 'medical_cards', ['medical_card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'medical_card_id')
    op.drop_column('patients', 'sex')
    op.drop_column('patients', 'birthday')
    op.drop_column('patients', 'middle_name')
    op.drop_column('patients', 'surname')
    op.drop_column('doctors', 'appointment_times')
    op.drop_column('doctors', 'specialization')
    op.drop_column('doctors', 'sex')
    op.drop_column('doctors', 'middle_name')
    op.drop_column('doctors', 'surname')
    op.drop_table('medical_cards')
    # ### end Alembic commands ###
