"""2

Revision ID: c2babe9064e6
Revises: 232e8001f763
Create Date: 2021-06-19 12:47:05.229574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2babe9064e6'
down_revision = '232e8001f763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'phone')
    # ### end Alembic commands ###
